### ISSUE TITLE
vagrant up DomainController1 problems

### ISSUE THREAD

**Issue by jdizon** [SharePointOscar/vagrant-ansible-packer-spfarm#1]
Hi Oscar,

I am going through your book at the moment but I am not able to get past the Chapter 3 exercise.

I keep getting this error message,

task path: /Users/josephdizon/Documents/lab/vagrant-ansible-packer-spfarm/ansible/plays/domaincontroller.yml:2
Using module file /usr/local/lib/python2.7/site-packages/ansible/modules/windows/setup.ps1
<192.168.2.19> ESTABLISH WINRM CONNECTION FOR USER: vagrant on PORT 5985 TO 192.168.2.19
checking if winrm_host 192.168.2.19 is an IPv6 address
objc[2881]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called.
objc[2881]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.

I am using a MacBook Pro 2018 running Mojave 10.14.2

It would be good if you can direct me to a working Ubuntu desktop which has all the tools installed as mentioned in the book.

**Comment by jdizon** [comment]
export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES

**Comment by sharepointoscar** [comment]
> export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES

What was the exact issue @jdizon ?  I'd like to compile a list of "gotchas" that may help others.  Would you mind elaborating a bit?

**Comment by jdizon** [comment]
Hi Oscar,


The issue is discussed on GitHub,


https://github.com/ansible/ansible/issues/32499


I am now experiencing a different issue with the screenshot attached.


I am trying to debug it and work out what the issue is.


?The error shows,


ntlm: the specified credentials were rejected by the server.


I have run this under macOS Sierra and macOS Mojave with the same result.


I was about to sell my macOS Sierra laptop but I just wanted to know if the GitHub codes run cleanly on macOS Sierra.


Regards,

Joseph Dizon

________________________________
